

const data  = [
    {
        id: 1,
        img: "card1.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 2,
        img: "card2.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 3,
        img: "card3.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 4,
        img: "card4.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 5,
        img: "card5.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 6,
        img: "card6.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 7,
        img: "card7.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 8,
        img: "card8.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 9,
        img: "card9.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 10,
        img: "card10.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 11,
        img: "card11.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 12,
        img: "card12.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 13,
        img: "card13.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 14,
        img: "card14.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 15,
        img: "card15.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    },
    {
        id: 16,
        img: "card16.png",
        name: "Desert King",
        duration: "per night",
        distance: "2345 km away",
        availability: "available for 2weeks stay",
        star: "./asset/starrating.png",
    }

]

export default data